framework:
    cache:
        pools:
            app.cache:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
            doctrine.result_cache_pool:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
            doctrine.system_cache_pool:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
