framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(resolve:REDIS_URL)%'
        pools:
            app.cache:
                adapter: cache.adapter.redis
                provider: '%env(resolve:REDIS_URL)%'
            doctrine.result_cache_pool:
                adapter: cache.adapter.redis
                provider: '%env(resolve:REDIS_URL)%'
            doctrine.system_cache_pool:
                adapter: cache.adapter.redis
                provider: '%env(resolve:REDIS_URL)%'
            doctrine.region_cache_pool:
                adapter: cache.adapter.redis
                provider: '%env(resolve:REDIS_URL)%'
