monolog:
    channels:
        - access
        - api
        - deprecation

when@dev:
    monolog:
        handlers:
            # --- ACCESS ---
            access:
                type: rotating_file
                path: "%kernel.logs_dir%/access.log"
                level: info
                channels: ["access"]
                max_files: 14

            # --- API ---
            api_handler:
                type: rotating_file
                path: "%kernel.logs_dir%/api.log"
                level: info
                channels: ["api"]
                max_files: 30

            # ===== SPLIT PAR NIVEAUX (.log) =====
            # DEBUG/INFO/NOTICE -> %env%_debug.log
            debug_file_raw:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%_debug.log"
                level: debug
                max_files: 7
            debug_filter:
                type: filter
                handler: debug_file_raw
                min_level: debug
                max_level: notice
                channels: ["!event", "!doctrine", "!console", "!access", "!api"]

            # ERROR ONLY -> %env%_error.log
            error_file_raw:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%_error.log"
                level: error
                max_files: 30
            error_filter:
                type: filter
                handler: error_file_raw
                accepted_levels: ["error"]
                channels: ["!event", "!doctrine", "!console", "!access", "!api"]

            # CRITICAL/ALERT/EMERGENCY -> %env%_critical.log
            critical_file_raw:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%_critical.log"
                level: critical
                max_files: 60
            critical_filter:
                type: filter
                handler: critical_file_raw
                min_level: critical
                max_level: emergency
                channels: ["!event", "!doctrine", "!console", "!access", "!api"]

            # Console (utile en dev)
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]

            # Deprecations séparées
            deprecation:
                type: rotating_file
                channels: [deprecation]
                path: "%kernel.logs_dir%/deprecations.log"
                max_files: 14


when@prod:
    monolog:
        handlers:
            access:
                type: rotating_file
                path: "%kernel.logs_dir%/access.log"
                level: info
                channels: ["access"]
                max_files: 30

            api_handler:
                type: rotating_file
                path: "%kernel.logs_dir%/api.log"
                level: info
                channels: ["api"]
                max_files: 60

            # Split par niveaux (.log)
            debug_file_raw:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%_debug.log"
                level: debug
                max_files: 14
            debug_filter:
                type: filter
                handler: debug_file_raw
                min_level: debug
                max_level: notice
                channels: ["!event", "!doctrine", "!console", "!access", "!api"]

            error_file_raw:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%_error.log"
                level: error
                max_files: 60
            error_filter:
                type: filter
                handler: error_file_raw
                accepted_levels: ["error"]
                channels: ["!event", "!doctrine", "!console", "!access", "!api"]

            critical_file_raw:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%_critical.log"
                level: critical
                max_files: 90
            critical_filter:
                type: filter
                handler: critical_file_raw
                min_level: critical
                max_level: emergency
                channels: ["!event", "!doctrine", "!console", "!access", "!api"]

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]

            deprecation:
                type: rotating_file
                channels: [deprecation]
                path: "%kernel.logs_dir%/deprecations.log"
                max_files: 60


when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                max_files: 3
