version: '3.8'

services:
  backend:
    image: php:8.2-fpm
    container_name: backend
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html

  server-web:
    image: nginx:alpine
    container_name: server-web
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    image: nouchka/sqlite3
    container_name: sqlite_db
    volumes:
      - ./data:/data