version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: .docker/php-fpm8/Dockerfile
    container_name: backend
    networks:
      - localhost-network
    volumes:
      - ./:/var/www/html
      - ./var/log:/var/log
  server-nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    container_name: server-nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - localhost-network
    volumes:
      - ./:/var/www/html
      - ./var/log/nginx:/var/log/nginx

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
networks:
  localhost-network:
    driver: bridge
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
