version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: .docker/php-fpm8/Dockerfile
    container_name: backend
    networks:
      - localhost-network
    volumes:
      - ./:/var/www/html
      - ./var/log:/var/log

  server-nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    container_name: server-nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - localhost-network
    volumes:
      - ./:/var/www/html
      - ./var/log/nginx:/var/log/nginx

networks:
  localhost-network:
    driver: bridge