CREATE DATABASE IF NOT EXISTS `${MYSQL_DATABASE}`;
DROP USER IF EXISTS `${MYSQL_USER}`@'%';
CREATE USER `${MYSQL_USER}`@'%' IDENTIFIED BY `${MYSQL_PASSWORD}`;
-- GRANT ALL ON `sf6_app`.* TO 'fayette'@'localhost' WITH GRANT OPTION;
GRANT SHOW `${MYSQL_DATABASE}`, SELECT ON mysql.* TO `${MYSQL_USER}`@'localhost';
-- GRANT ALL ON `${MYSQL_DATABASE}`.* TO `${MYSQL_USER}`@'localhost' IDENTIFIED BY `${MYSQL_PASSWORD}`  WITH GRANT OPTION;
FLUSH PRIVILEGES;