-- CREATE DATABASE IF NOT EXISTS `${MYSQL_DATABASE}`;

-- DROP USER IF EXISTS `${MYSQL_USER}`@'%';
-- CREATE USER `${MYSQL_USER}`@'%' IDENTIFIED BY `${MYSQL_PASSWORD}`;

-- GRANT ALL ON `sf6_app`.* TO `${MYSQL_USER}`@'%' WITH GRANT OPTION;
-- GRANT SHOW `${MYSQL_DATABASE}` ON *.* TO  `${MYSQL_USER}`@'%';
-- GRANT SELECT ON mysql.* TO `${MYSQL_USER}`@'%';
-- GRANT ALL ON `${MYSQL_DATABASE}`.* TO `${MYSQL_USER}`@'localhost' IDENTIFIED BY `${MYSQL_PASSWORD}`  WITH GRANT OPTION;

-- FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS `sf6_app`;

DROP USER IF EXISTS 'fayette'@'%';
CREATE USER 'fayette'@'%' IDENTIFIED BY 'patrician';

GRANT ALL ON `sf6_app`.* TO 'fayette'@'%' WITH GRANT OPTION;
GRANT SHOW DATABASES ON *.* TO 'fayette'@'%';
GRANT SELECT ON mysql.* TO 'fayette'@'%';

FLUSH PRIVILEGES;