parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $targetDirectory: '%images_directory%'
            $circularReferenceHandler: '@App\Handler\CircularReferenceHandler'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\Service\ImageUploadService: ~

    App\Handler\CircularReferenceHandler:
        public: true

    App\EventListener\CorsListener:
        public: true
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    App\EventListener\CheckCustomerExistsListener:
        public: true
        tags:
            - { name: kernel.event_listener }

    App\EventListener\ExceptionListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception' }

    Symfony\Component\Serializer\Normalizer\ObjectNormalizer:
        public: true
        arguments:
            $defaultContext:
                circular_reference_handler: '@App\Handler\CircularReferenceHandler'

    App\Command\UgoCustomersImportCommand:
        public: true
        tags: [ 'console.command' ]

    App\Command\UgoPurchasesImportCommand:
        public: true
        tags: [ 'console.command' ]

    App\Command\UgoOrdersImportCommand:
        public: true
        tags: [ 'console.command' ]

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
