parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'

services:
    # 🧩 configuration par défaut
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $targetDirectory: '%images_directory%'
            $circularReferenceHandler: '@App\Handler\CircularReferenceHandler'
            # --- SMS ---
            $providerUrl: '%env(SMS_PROVIDER_URL)%'
            $apiKey: '%env(SMS_API_KEY)%'
            $senderName: '%env(default::SMS_SENDER)%'
            $enabled: '%env(bool:SMS_ENABLED)%'
            # --- MAIL ---
            $defaultFrom: '%env(DEFAULT_MAIL_FROM)%'
            $asyncDefault: '%env(bool:MAILER_ASYNC_DEFAULT)%'
            $mailerEnabled: '%env(bool:MAILER_ENABLED)%'

    app.redis:
        class: Redis
        factory: [ 'Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection' ]
        arguments:
            - '%env(resolve:REDIS_URL)%'

    session.handler.redis:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        arguments:
            - '@app.redis'
            - { prefix: 'sess_', ttl: 1800 }

    App\DataTransformer\UserInputDataTransformer:
        arguments:
            $passwordHasher: '@security.user_password_hasher'
        tags: [ 'api_platform.data_transformer' ]

    App\DataTransformer\UserOutputProvider:
        tags: [ 'api_platform.state_provider' ]

    App\DataTransformer\OrderOutputDataTransformer:
        tags:
            - { name: 'api_platform.state_processor' }

    App\Service\ImageUploadService: ~

    App\Handler\CircularReferenceHandler:
        public: true

    App\EventListener\CorsListener:
        public: true
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    App\EventListener\CheckCustomerExistsListener:
        public: true
        tags:
            - { name: kernel.event_listener }

    App\EventListener\ExceptionListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception' }

    Symfony\Component\Serializer\Normalizer\ObjectNormalizer:
        public: true
        arguments:
            $defaultContext:
                circular_reference_handler: '@App\Handler\CircularReferenceHandler'

    App\Command\UgoCustomersImportCommand:
        public: true
        tags: [ 'console.command' ]

    App\Command\UgoPurchasesImportCommand:
        public: true
        tags: [ 'console.command' ]

    App\Command\UgoOrdersImportCommand:
        public: true
        tags: [ 'console.command' ]

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Message/'
